# Vectors Practice

In this chapter we will work with vectors and code Gramm-Schmidt Orthonormalization Algorithm

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import lovely_numpy as ln
import json_tricks



In [9]:
inputs = json_tricks.load('/Users/thanakritp/Documents/Thanakrit_workspace/Class/linear-algrebra-1/linear-algebra-part-1/.laborantum/texts/course/1. Vectors/Vectors Practice/inputs/inputs.json')
# inputs1 = json_tricks.load('.inputs2.json')

answers = {}

In your input you have arrys of shape $N \times 2$, which means that you have 2 vectors both having N coordinates

In [10]:
for one_input in inputs:
    print(one_input)
    print(ln.lovely(one_input['X']))

OrderedDict({'X': array([[  2,   5],
       [-10,  -7]])})
array[2, 2] i64 n=4 x∈[-10, 5] μ=-2.500 σ=6.185 [[2, 5], [-10, -7]]
OrderedDict({'X': array([[-7, -3],
       [-1,  9],
       [ 8, -6],
       [-4,  2],
       [-9, -4]])})
array[5, 2] i64 n=10 x∈[-9, 9] μ=-1.500 σ=5.784 [[-7, -3], [-1, 9], [8, -6], [-4, 2], [-9, -4]]
OrderedDict({'X': array([[  4,   7],
       [ -5,   3],
       [ -2,  -1],
       [  9,   6],
       [  9,  -5],
       [  5,   5],
       [-10,   8],
       [ -7,   7],
       [  9,   9]])})
array[9, 2] i64 n=18 x∈[-10, 9] μ=2.833 σ=6.039
OrderedDict({'X': array([[  4,  -3],
       [-10,  -9],
       [ -1, -10],
       [  0,  -7],
       [  1,   8]])})
array[5, 2] i64 n=10 x∈[-10, 8] μ=-2.700 σ=5.900 [[4, -3], [-10, -9], [-1, -10], [0, -7], [1, 8]]
OrderedDict({'X': array([[ -8, -10],
       [-10,  -6],
       [ -5,  -4],
       [ -2,   7],
       [  5,  -6],
       [ -1,   0],
       [ -9,  -9],
       [ -3,  -1],
       [ -7,  -4]])})
array[9, 2] i64 n=18 x∈[-

# Task 1. Vector lenghts

- Write a function that calculates vector lengths, answer should return array of shape $2$
- Apply this function to all the inputs

In [13]:
def get_lengths(X):
    res = np.sqrt((X**2).sum(axis=0))
    return res

In [14]:
answers['lengths'] = [
    get_lengths(**inp) for inp in inputs
]
answers['lengths']

[array([10.19803903,  8.60232527]),
 array([14.52583905, 12.08304597]),
 array([21.49418526, 18.41195264]),
 array([10.86278049, 17.40689519]),
 array([18.92088793, 18.30300522]),
 array([11.61895004, 18.38477631]),
 array([22.02271555, 18.57417562]),
 array([13.49073756,  6.164414  ]),
 array([15.03329638, 13.34166406]),
 array([10.04987562,  6.244998  ]),
 array([14.59451952, 14.73091986]),
 array([12.04159458,  9.94987437]),
 array([10.67707825, 14.76482306]),
 array([12.12435565, 16.673332  ]),
 array([16.40121947, 10.39230485]),
 array([14.62873884, 17.77638883]),
 array([15.16575089,  9.48683298]),
 array([20.73644135, 12.60952021]),
 array([17.63519209, 18.57417562]),
 array([9.64365076, 9.64365076]),
 array([16.55294536, 15.71623365]),
 array([12.20655562, 12.36931688]),
 array([ 9.8488578 , 10.19803903]),
 array([19.39071943, 17.77638883]),
 array([15.55634919, 19.94993734]),
 array([11.13552873, 12.60952021]),
 array([8.60232527, 4.47213595]),
 array([ 7.34846923, 12.80624847

# Task 2. Vector directions

- Write a function that calculates vector directions. Result should be of the same shape as the original array X
- Use $10^{-8}$ addition in division to avoid division by zero
- Apply this function to all arrays in the inputs

In [15]:
def get_directions(X):
    res = None
    lenght = np.sqrt((X**2).sum(axis=0))
    res = X / lenght

    return res



In [16]:
answers['directions'] = [
    get_directions(**inp) for inp in inputs
]
answers['directions']

[array([[ 0.19611614,  0.58123819],
        [-0.98058068, -0.81373347]]),
 array([[-0.48189987, -0.24828177],
        [-0.06884284,  0.7448453 ],
        [ 0.55074271, -0.49656353],
        [-0.27537136,  0.16552118],
        [-0.61958555, -0.33104236]]),
 array([[ 0.18609684,  0.38018781],
        [-0.23262105,  0.16293763],
        [-0.09304842, -0.05431254],
        [ 0.41871789,  0.32587527],
        [ 0.41871789, -0.27156272],
        [ 0.23262105,  0.27156272],
        [-0.46524211,  0.43450036],
        [-0.32566947,  0.38018781],
        [ 0.41871789,  0.4888129 ]]),
 array([[ 0.36822985, -0.1723455 ],
        [-0.92057462, -0.51703649],
        [-0.09205746, -0.57448499],
        [ 0.        , -0.40213949],
        [ 0.09205746,  0.45958799]]),
 array([[-0.42281314, -0.54635836],
        [-0.52851642, -0.32781502],
        [-0.26425821, -0.21854335],
        [-0.10570328,  0.38245086],
        [ 0.26425821, -0.32781502],
        [-0.05285164,  0.        ],
        [-0.47566478

# Step 3. Visualization

We will visualize vectors and directions using `matplotlib` 

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 10))
ax = plt.gca()
X = inputs[0]['X']
vecs = np.concatenate([np.zeros_like(X), X.T], axis=1)
X, Y, U, V = zip(*vecs)

print(X, Y, U, V)

ax.quiver(X, Y, U, V, angles='xy', scale_units='xy', scale=1, color = 'red')

X = answers['directions'][0] * 2
norms = np.concatenate([np.zeros_like(X), X.T], axis=1)
X, Y, U, V = zip(*norms)

print(X, Y, U, V)
ax.quiver(X, Y, U, V, angles='xy', scale_units='xy', scale=1, color = 'blue')
ax.set_xlim([-10, 10])
ax.set_ylim([-10, 10])
plt.draw()
plt.grid()
plt.legend(['original', 'normalized'])
plt.show()


# Task 4. Scalar Product

Write a function that calculates
- cosine distance between the vectors
- use $10^{-8}$ additional constant in the denominator for the sake of numerical stability

In [ ]:
def get_cosine(X):
    res = None
    ## YOUR CODE HERE
    return res

In [ ]:
answers['cosine'] = [
    get_cosine(**inp) for inp in inputs
]

In [ ]:
print(answers['cosine'][0])

# Task 5. Orthonormalization

Create a pair of orthonormal vectors
- Take the first vector and normalize it
- Take the second vector, remove the collinear component to the first one
- Normalize it

In [ ]:

def get_orthonormal(X):
    res = X.copy().astype('float32')
    ## YOUR CODE HERE
    return res

In [ ]:
answers['orthonormal'] = [
    get_orthonormal(**inp) for inp in inputs
]

# 6. Visualization

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 10))
ax = plt.gca()
X = inputs[0]['X']
print(X)
vecs = np.concatenate([np.zeros_like(X), X.T], axis=1)
X, Y, U, V = zip(*vecs)
ax.quiver(X, Y, U, V, angles='xy', scale_units='xy', scale=1, color = 'red')

X = answers['orthonormal'][0]
print(X)
norms = np.concatenate([np.zeros_like(X), X.T], axis=1)
X, Y, U, V = zip(*norms)
ax.quiver(X, Y, U, V, angles='xy', scale_units='xy', scale=1, color = 'blue')
ax.set_xlim([-5, 5])
ax.set_ylim([-5, 5])
plt.draw()
plt.grid()
plt.legend(['original', 'orthonormalized'])
plt.show()


# 7. Saving the answer

In [ ]:
json_tricks.dump(answers, '.answer.json')