In [2]:
import numpy as np
import json_tricks

answer = {}


inputs = json_tricks.load('inputs.json')


# Matrix Product II

$$A_{5 \times 10} \  B_{10 \times 2}\ C_{2 \times 30}\ D_{30 \times 3}\ E_{3 \times 9}$$

1. What will be the shape of the resulting matrix?
2. How many multiplication of numbers are required at best?

In [3]:
answer['task1'] = {
    '1': [5,9],
    '2': 424
}



# Numpy expression

Using Numpy, write a function that calculates the 
following expression:

$$\exp(A^T(B + 2C) + 3I) \mathbf x,$$

where $I$ is an identity matrix of the necessary shape.

In [4]:
def numpy_expression(A, B, C, x):
    step1 = B + 2 * C
    
    step2 = A.T @ step1
    
    I = np.eye(step2.shape[0], step2.shape[1])  
    step3 = step2 + (3 * I)
    
    step4 = np.exp(step3)
    
    res = step4 @ x
    
    return res

In [5]:
answer['task2'] = []
for one_input in inputs['task2']:
    answer['task2'].append(numpy_expression(**one_input))
answer['task2']

[array([[-8.27590894e+033],
        [-6.29718677e+100],
        [-1.60179377e+088],
        [-7.79228831e+010],
        [-4.60139214e+144],
        [-1.12933457e+070],
        [-9.84176105e+082],
        [-2.62446961e+083]]),
 array([[-8.43835667e+27],
        [ 1.66183588e+69]]),
 array([[ 5.97988376e+120],
        [-7.66898691e+144],
        [ 5.31657438e+086],
        [ 2.58854587e+171]]),
 array([[ 8.14713560e+109],
        [-5.74229105e+097],
        [ 1.18332459e+123],
        [-2.22611614e+233],
        [ 2.71429001e+150],
        [-7.27213245e+083]]),
 array([[-1.96422332e+087],
        [ 2.40167650e+156],
        [-4.91518686e+002]]),
 array([[-3.71266816e+147],
        [-4.93725410e+192],
        [-3.02285533e+111]]),
 array([[-4.69932272e+174],
        [-1.86160358e+068],
        [ 2.58673893e+016],
        [-1.96038349e+048],
        [ 1.53621676e+181],
        [-2.26460264e+024]]),
 array([[ 3.56029316e+54],
        [-7.91122426e+43],
        [-4.99186955e+01],
        [-4

# Einstein's Rule

In *Tensor Algebra*, a direct generalization of the Linear Algebra to the case of $N$-dimentional tables called *tensors* (normal matrix), the Einstein's rule exists.

It works as follows: if you see a duplicating upper and lower index in the formula, that means, this index convolves.

For example, the following tensor expression, summation and matrix product are equivalent:

$$a_k^l b_l^m = \sum_{l=1}^L a_k^l b_l^m = AB$$

In this notation subscript means row index and superscript means column index.

<details>
<summary> Note </summary>

> [!NOTE]
> Also at some point it will be important to know that:
> * lower index represents a contravariant dimension of a
> tensor
> * upper index represents a covariant dimension 
> of tensor. But let us omit this part for now.

</details>

# Task

Calculate the following expression written using Einstein's 
rule:

$$a_k^m b_m^n c_n^o d_l^k$$

In [6]:
def einsteins_rule(A, B, C, D):
    res = A
    #your code here
    res = np.matmul(res, B)
    res = np.matmul(res, C)
    res = np.matmul(D, res)
    return res

In [7]:
answer['task3'] = []
for one_input in inputs['task3']:
    answer['task3'].append(einsteins_rule(**one_input))
answer['task3']

[array([[ 48506,  -8208,  -2323, -42632, -37130,   6317,   -346,  28727],
        [-39432,  -2813,  12000,  37266,  28457, -28774,   9193,   1945],
        [ 23582,  15271, -19458,   2009, -13383, -23067,    821, -35268],
        [ -6730,   8065,   3048,  19644,  13563,  -5324,  -3583, -17783],
        [ 29391,   8495, -22202, -25782, -12722,   2634, -21327,   2777],
        [ 23946, -12401,  10651, -18540, -39014, -14482,  20230,  24802],
        [-10750,  25247, -37835,  -5284,    238,   1056, -32336, -24844],
        [-12009,  -6748,  41340,  16307,   4256,  65230, -13003,   9533]]),
 array([[-830,  830],
        [-516,  516]]),
 array([[ 3737, -3005,  2001,  4167],
        [10260, -5360,  4416,  5317],
        [ 9164,  -304,  4252,  2955],
        [ 1789, 12291,  2981,   902]]),
 array([[ -7132, -43627,  26225, -37002,  -4029,  22759],
        [ 12604, -34143,  19871, -12877,  -4428,  18386],
        [ 10135,    471,    485,   7453,   -882,  -2864],
        [ -7921,  25168, -14713,

# Diagonal Matrix Product

You are given two square matrices: $A$ and $D$, where $A$ is a 
full matrix and $D$ is a diagonal matrix:

$$
A = \begin{bmatrix}
- & \mathbf a_1 & - \\
& \vdots & \\
- & \mathbf a_N & - \\
\end{bmatrix}
$$

$$
D = \textrm{diag}(d_1, d_2, \dots, d_N) = \begin{bmatrix}
d_1 & & & & \\
& d_2 & & & \\
& & d_3 & & \\
& & & \ddots & \\
& & & & d_N 
\end{bmatrix}
$$

Write a program to calculate the result of $DA$ and $AD$ in 
the fastest possible way.

In [8]:
def diag_prod_DA(A, D):
    d = np.diag(D)
    res = A * d[:, None]
    return res

def diag_prod_AD(A, D):
    d = np.diag(D)
    res = A * d[None, :]
    return res

In [9]:
answer['task4_1'] = []
answer['task4_2'] = []
for one_input in inputs['task4']:
    answer['task4_1'].append(diag_prod_DA(**one_input))
    answer['task4_2'].append(diag_prod_AD(**one_input))
answer['task4_1']
# answer['task4_2']

[array([[ -4,   2, -20, -20,   8, -18,  10,  -6],
        [  2, -10,   5,  -4,  -6,  -8,   1,   5],
        [ 24, -18,   9, -18,  12,  18,   9,  27],
        [ 54,  -9, -45, -45,  36,  63,  90,  54],
        [ -8, -48, -56, -72,  72,  -8,  64, -80],
        [-42,  14, -49,  35,  35, -63,  42,  63],
        [ -8, -56,  64,  80,  80, -64,   0,  48],
        [  6, -48, -60, -60, -18,  -6,   0,   6]]),
 array([[-36,  -6],
        [ -3,  24]]),
 array([[  0,   0,   0,   0],
        [ 49, -56, -63,  70],
        [ 18,  12,   2,   8],
        [  0,   0,   0,   0]]),
 array([[ 14,  35,  63, -42,  42,  35],
        [  4,  -4, -20, -12, -36,   4],
        [ 18, -36,  -9,  18,  54,  27],
        [-72,   0, -80,  64, -56,  64],
        [  0,  24,   0,  56, -48,  32],
        [-27, -72, -81,  36, -54, -90]]),
 array([[-20,  -5,  35],
        [-32,  36,   4],
        [-16,   0, -40]]),
 array([[ 63, -36,  36],
        [  0,  35,   5],
        [-35,  63,  14]]),
 array([[ 21,  15,  12, -21,  18, -27]

# Sparse Matrix Product

You are given two matrices of the same shape: $A$ and $B$. Matrix $A$ is full
and is given in the form of `numpy.ndarray`.

The second matrix $B$ is **sparse**. That means that the 
majority of the items are equal to $0$ except for $M$. This matrix is given
as a set of non-zero elements of this matrix in form of $3 \times M$ `numpy.ndarray` as row-column-value tuple (COO sparse matrix form):

$$
\begin{bmatrix}
r_1 & c_1 & v_1 \\
r_2 & c_2 & v_2 \\
& \vdots & \\
r_M & c_M & v_M \\
\end{bmatrix}
$$

If in this struct two items correspond to the same location, consider the latter is correct.

Write the most efficient program that calculates $AB$.

Also return the ratio between the number of multiplication operations that are needed to calculate the sparse product and the number of operations for full product.

In [ ]:
def sparse_matrix_product(A, B_sparse):
    res = A
    ratio = 0
    

    return res, ratio


In [11]:
answer['task5'] = []
for one_input in inputs['task5']:
    answer['task5'].append(sparse_matrix_product(**one_input))

In [12]:
json_tricks.dump(answer, '.answer.json')

'{"task1": {"1": [5, 9], "2": 424}, "task2": [{"__ndarray__": [[-8.275908938500257e+33], [-6.29718677025919e+100], [-1.6017937662626578e+88], [-77922883127.9092], [-4.601392143156699e+144], [-1.1293345702805571e+70], [-9.841761046154011e+82], [-2.6244696123077364e+83]], "dtype": "float64", "shape": [8, 1], "Corder": true}, {"__ndarray__": [[-8.438356668741454e+27], [1.6618358824416089e+69]], "dtype": "float64", "shape": [2, 1], "Corder": true}, {"__ndarray__": [[5.979883758421911e+120], [-7.668986905261165e+144], [5.316574383475204e+86], [2.5885458717800575e+171]], "dtype": "float64", "shape": [4, 1], "Corder": true}, {"__ndarray__": [[8.147135599799323e+109], [-5.742291049527847e+97], [1.1833245862047797e+123], [-2.2261161390770436e+233], [2.7142900080228685e+150], [-7.272132448230352e+83]], "dtype": "float64", "shape": [6, 1], "Corder": true}, {"__ndarray__": [[-1.964223318681796e+87], [2.4016764986906346e+156], [-491.5186855815347]], "dtype": "float64", "shape": [3, 1], "Corder": tr